// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleStateMachineEditor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSimpleStateMachineEditorPackageString = "c846a7b8-b60e-488b-9362-e6f81d9fc027";
        public static Guid guidSimpleStateMachineEditorPackage = new Guid(guidSimpleStateMachineEditorPackageString);

        public const string guidDesignControlCmdUIContextString = "aab25516-9070-4676-a93a-43b27637c36c";
        public static Guid guidDesignControlCmdUIContext = new Guid(guidDesignControlCmdUIContextString);

        public const string guidSimpleStateMachineEditorPackageCmdSetString = "676801a7-f00d-4e83-89eb-a85e3c47f64a";
        public static Guid guidSimpleStateMachineEditorPackageCmdSet = new Guid(guidSimpleStateMachineEditorPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int StateMachineToolbarId = 0x1020;
        public const int AlignmentSubmenutMenuId = 0x1021;
        public const int StateMachineContextMenuId = 0x1022;
        public const int DesignControlToolsSubmenuId = 0x1023;
        public const int HorizontalAlignmentSubmenuMenuId = 0x1024;
        public const int VerticalAlignmentSubmenuMenuId = 0x1025;
        public const int StateIconContextMenuId = 0x1027;
        public const int EventTypeIconContextMenuId = 0x1028;
        public const int TransitionIconContextMenuId = 0x1029;
        public const int StateMachineToolbarAddGroupId = 0x102A;
        public const int StateMachineToolbarRemoveGroupId = 0x102B;
        public const int DesignControlSubmenuGroupId = 0x102D;
        public const int StateIconContextMenuGroupId = 0x102F;
        public const int EventTypeIconContextMenuGroupId = 0x1030;
        public const int TransitionIconContextMenuGroupId = 0x1031;
        public const int DesignControlToolsMenuGroupId = 0x1032;
        public const int DesignControlViewMenuGroupId = 0x1033;
        public const int AlignmentSubmenuGroupId = 0x1034;
        public const int HorizontalAlignmentSubmenuGroupId = 0x1035;
        public const int VerticalAlignmentSubmenuGroupId = 0x1056;
        public const int SetIconDisplayColorsComboListId = 0x1037;
        public const int ActionIconContextMenuId = 0x1038;
        public const int ActionIconContextMenuGroupId = 0x1039;
        public const int LayerIconContextMenuId = 0x103A;
        public const int LayerIconContextMenuGroupId = 0x103B;
        public const int AddEventTypeCommandId = 0x0100;
        public const int AddStateCommandId = 0x0102;
        public const int AddTransitionCommandId = 0x0103;
        public const int AlignBottomCommandId = 0x0104;
        public const int AlignHorizontalCenterCommandId = 0x0105;
        public const int AlignLeftCommandId = 0x0106;
        public const int AlignRightCommandId = 0x0107;
        public const int AlignTopCommandId = 0x0108;
        public const int AlignVerticalCenterCommandId = 0x0109;
        public const int DeleteCommandId = 0x010A;
        public const int DistributeHorizontallyCommandId = 0x010B;
        public const int DistributeVerticallyCommandId = 0x010C;
        public const int SelectNewDestinationCommandId = 0x010F;
        public const int SelectNewSourceCommandId = 0x0110;
        public const int SetIconDisplayColorsComboId = 0x0111;
        public const int SortCommandId = 0x0113;
        public const int StartStateCommandId = 0x0114;
        public const int cmdidActionsToolWindowCommand = 0x0115;
    }
}